var files =
[
    [ "src/com/axcoto/shinjuku/maki/DeviceItem.java", "_device_item_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/Finder.java", "_finder_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/IdRegister.java", "_id_register_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/ItemAdapter.java", "_item_adapter_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/MyHttpServer.java", "_my_http_server_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/NanoHTTPD.java", "_nano_h_t_t_p_d_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/Remote.java", "_remote_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/Song.java", "_song_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/SongAdapter.java", "_song_adapter_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/SongBook.java", "_song_book_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/Unicode.java", "_unicode_8java.html", null ],
    [ "src/com/axcoto/shinjuku/maki/XMLParser.java", "_x_m_l_parser_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/AlertDialogManager.java", "_alert_dialog_manager_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/CommonUtilities.java", "_common_utilities_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/ConfigActivity.java", "_config_activity_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/ConnectionDetector.java", "_connection_detector_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/DeviceActivity.java", "_device_activity_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/GCMIntentService.java", "_g_c_m_intent_service_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/MainActivity.java", "_main_activity_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/MyApp.java", "_my_app_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/RemoteKeyButton.java", "_remote_key_button_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/RootActivity.java", "_root_activity_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/ServerUtilities.java", "_server_utilities_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/SongActivity.java", "_song_activity_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/UserEmailFetcher.java", "_user_email_fetcher_8java.html", null ],
    [ "src/com/axcoto/shinjuku/sushi/WakeLocker.java", "_wake_locker_8java.html", null ],
    [ "src/com/robobunny/SeekBarPreference.java", "_seek_bar_preference_8java.html", null ]
];